<a href="https://colab.research.google.com/github/arnavarya001/DATA-SCIENCE/blob/main/lect06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('student_data.csv')

In [ ]:
df.groupby('placement_status')['placement_status'].agg('count')

placement_status
Not Placed    1644
Placed        8356
Name: placement_status, dtype: int64

In [ ]:
df.groupby('placement_status')['exam_score'].agg('mean')

placement_status
Not Placed    59.804653
Placed        91.996556
Name: exam_score, dtype: float64

In [ ]:
df.groupby('placement_status')['study_hours'].agg('mean')

placement_status
Not Placed    3.130170
Placed        6.552178
Name: study_hours, dtype: float64

In [ ]:
df.groupby('study_hours')['exam_score'].agg('mean')

study_hours
1     71.264562
2     75.169142
3     78.974939
4     81.845483
5     84.964142
6     88.620043
7     90.539568
8     93.297697
9     95.462126
10    96.574628
11    97.303283
Name: exam_score, dtype: float64

In [ ]:
def grades(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'


df['grade'] = df['exam_score'].apply(grades)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,grade
0,7,56,8,7,10,62,100.00,Placed,A
1,4,69,5,3,8,56,100.00,Placed,A
2,11,60,7,6,10,45,100.00,Placed,A
3,8,99,9,8,4,55,90.17,Placed,A
4,5,52,8,6,8,40,78.82,Placed,C
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,D
9996,7,98,6,9,4,87,100.00,Placed,A
9997,10,44,8,5,10,37,95.94,Placed,A
9998,10,75,7,5,8,52,88.61,Placed,B
9999,2,70,6,11,16,52,78.96,Placed,C

In [ ]:
import pandas as pd

student = pd.DataFrame({
    'Name': ['Arnav', 'Rahul', 'Amit','Yash'],
    'department id': [0,3,5,7]
}, index=[1, 2, 3,4])

department = pd.DataFrame({
    'Marks': [85, 90, 78, 32],
    'department': ['cse','ece','mech','civil']
}, index=[1, 2, 3,4])

result = student.join(department)
display(result)

    Name  department id  Marks department
1  Arnav              0     85        cse
2  Rahul              3     90        ece
3   Amit              5     78       mech
4   Yash              7     32      civil

In [ ]:
import pandas as pd

student = pd.DataFrame({
    'Name': ['Arnav', 'Rahul', 'Amit', 'Yash'],
    'department id': [0, 3, 5, 7]
}, index=[1, 2, 3, 4])

department = pd.DataFrame({
    'Marks': [85, 90, 78, 32],
    'department': ['cse', 'ece', 'mech', 'civil']
}, index=[1, 2, 3, 4])

result = student.join(department, how='inner')
display(result)

    Name  department id  Marks department
1  Arnav              0     85        cse
2  Rahul              3     90        ece
3   Amit              5     78       mech
4   Yash              7     32      civil